Move installing build-deps back to configure When using --dvb_dir option the kernelpatch scripts will never be called

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -235,6 +235,47 @@ fi
 # Begin Debian Section
 #
 
+# Install build dependencies for FFdecsawrapper
+
+if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
+  if ! dpkg-query -l libv4l-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libv4l-dev, marking for installation.
+"
+    apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
+  fi
+
+  if ! dpkg-query -l libproc-processtable-perl > /dev/null 2>&1; then
+    echo "
+Missing dependency libproc-processtable-perl, marking for installation.
+"
+    apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
+  fi
+
+  if ! dpkg-query -l libssl-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libssl-dev, marking for installation.
+"
+    apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
+  fi
+
+  if ! dpkg-query -l build-essential > /dev/null 2>&1; then
+    echo "
+Missing dependency build-essential, marking for installation.
+"
+    apt-get install build-essential -y || die "Error installing dependency build-essential"
+  fi
+
+  if uname -a | grep 'Debian' > /dev/null  2>&1; then
+    if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
+      echo "
+Missing dependency linux-headers-`uname -r`, marking for installation.
+"
+      apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
+    fi
+  fi
+fi
+
 if test "x$dvb_path" = "x"; then
   if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
     if uname -a | grep 'Debian' > /dev/null  2>&1; then
@@ -267,6 +308,48 @@ fi
 #
 # Begin Ubuntu Section
 #
+
+# Install build dependencies for FFdecsawrapper
+
+if echo $OS | grep 'Ubuntu' 2>&1 1>/dev/null; then
+  if ! dpkg-query -l libv4l-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libv4l-dev, marking for installation.
+"
+    sudo apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
+  fi
+
+  if ! dpkg-query -l libproc-processtable-perl > /dev/null 2>&1; then
+    echo "
+Missing dependency libproc-processtable-perl, marking for installation.
+"
+    sudo apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
+  fi
+
+  if ! dpkg-query -l libssl-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libssl-dev, marking for installation.
+"
+    sudo apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
+  fi
+
+  if ! dpkg-query -l build-essential > /dev/null 2>&1; then
+    echo "
+Missing dependency build-essential, marking for installation.
+"
+    sudo apt-get install build-essential -y || die "Error installing dependency build-essential"
+  fi
+
+  if uname -a | grep 'Ubuntu' > /dev/null  2>&1; then
+    if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
+      echo "
+Missing dependency linux-headers-`uname -r`, marking for installation.
+"
+      sudo apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
+    fi
+  fi
+fi
+
 
 if test "x$dvb_path" = "x"; then
   if echo $OS | grep 'Ubuntu' 2>&1 1>/dev/null; then
