Remove Ubuntu stuff from stable branch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -199,7 +199,7 @@ Aborting...
 fi
 
 #
-# Begin Debian/Ubuntu Section
+# Begin Debian Section
 #
 
 # First get some info on what we are running
@@ -209,24 +209,21 @@ if [ -f /usr/bin/lsb_release ]; then
   RELEASE=$( lsb_release -sc )
 fi
 
-# The rest of the Debian/Ubuntu section
+# The rest of the Debian section
 # depends on the outcome of next line
 
-if [ $OS == Ubuntu ] || [ $OS == Debian ] ; then
+if [ $OS == Debian ] ; then
 
-# If we run Debian, make sure
-# that we are running as root
+# Make sure that we are running as root
 
-  if [ $OS == Debian ] ; then
-    if ! echo "$(whoami)" | grep "root" > /dev/null 2>&1; then
-      echo "
+  if ! echo "$(whoami)" | grep "root" > /dev/null 2>&1; then
+    echo "
 You should run as root.
 
 Aborting...
 "
-      make clean > /dev/null 2>&1
-      exit 0
-    fi
+    make clean > /dev/null 2>&1
+    exit 0
   fi
 
 # Check if FFdecsawrapper is running
@@ -241,25 +238,13 @@ It should be stopped before proceeding.
     confirmyes "Do you want to stop FFdecsawrapper now? [Y/n]"
     if [ $(echo $?) -eq 0 ]; then
       if test -e /etc/init.d/ffdecsawrapper; then
-        if [ $OS == Debian ] ; then
-          /etc/init.d/ffdecsawrapper stop
-          sleep 3
-          rmmod dvbloopback > /dev/null 2>&1
-        else
-          sudo /etc/init.d/ffdecsawrapper stop
-          sudo sleep 3
-          sudo rmmod dvbloopback > /dev/null 2>&1
-        fi
+        /etc/init.d/ffdecsawrapper stop
+        sleep 3
+        rmmod dvbloopback > /dev/null 2>&1
       else
-        if [ $OS == Debian ] ; then
-          killall -9 ffdecsawrapper
-          sleep 3
-          rmmod dvbloopback > /dev/null 2>&1
-        else
-          sudo killall -9 ffdecsawrapper
-          sudo sleep 3
-          sudo rmmod dvbloopback > /dev/null 2>&1
-        fi
+        killall -9 ffdecsawrapper
+        sleep 3
+        rmmod dvbloopback > /dev/null 2>&1
       fi
     fi
   fi
@@ -270,62 +255,42 @@ It should be stopped before proceeding.
     echo "
 Missing dependency gettext, marking for installation.
 "
-    if [ $OS == Debian ] ; then
-      apt-get install gettext -y || die "Error installing dependency gettext"
-    else
-      sudo apt-get install gettext -y || die "Error installing dependency gettext"
-    fi
+    apt-get install gettext -y || die "Error installing dependency gettext"
   fi
 
   if ! dpkg-query -l libv4l-dev > /dev/null 2>&1; then
     echo "
 Missing dependency libv4l-dev, marking for installation.
 "
-    if [ $OS == Debian ] ; then
-      apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
-    else
-      sudo apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
-    fi
+    apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
   fi
 
   if ! dpkg-query -l libproc-processtable-perl > /dev/null 2>&1; then
     echo "
 Missing dependency libproc-processtable-perl, marking for installation.
 "
-    if [ $OS == Debian ] ; then
-      apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
-    else
-      sudo apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
-    fi
+    apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
   fi
 
   if ! dpkg-query -l libssl-dev > /dev/null 2>&1; then
     echo "
 Missing dependency libssl-dev, marking for installation.
 "
-    if [ $OS == Debian ] ; then
-      apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
-    else
-      sudo apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
-    fi
+    apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
   fi
 
   if ! dpkg-query -l build-essential > /dev/null 2>&1; then
     echo "
 Missing dependency build-essential, marking for installation.
 "
-    if [ $OS == Debian ] ; then
-      apt-get install build-essential -y || die "Error installing dependency build-essential"
-    else
-      sudo apt-get install build-essential -y || die "Error installing dependency build-essential"
-    fi
+    apt-get install build-essential -y || die "Error installing dependency build-essential"
   fi
 
-# If we are running a Debian or Ubuntu kernel
+# If we are running a Debian kernel
 # we need the headers installed.
 # But don't install headers if we are running
 # a vanilla kernel
-# uname -a does not return Debian or Ubuntu
+# uname -a does not return Debian
 # when we are running a vannila kernel
 
   if uname -a | grep 'Debian' > /dev/null  2>&1; then
@@ -334,15 +299,6 @@ Missing dependency build-essential, marking for installation.
 Missing dependency linux-headers-`uname -r`, marking for installation.
 "
       apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
-    fi
-  fi
-
-  if uname -a | grep 'Ubuntu' > /dev/null  2>&1; then
-    if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
-      echo "
-Missing dependency linux-headers-`uname -r`, marking for installation.
-"
-      sudo apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
     fi
   fi
 
@@ -367,11 +323,7 @@ Missing dependency linux-headers-`uname -r`, marking for installation.
       echo "
 Missing dependency g++-$CCKERNEL, marking for installation.
 "
-      if [ $OS == Debian ] ; then
-        apt-get install g++-$CCKERNEL -y || die "Error installing dependency g++-$CCKERNEL"
-      else
-        sudo apt-get install g++-$CCKERNEL -y || die "Error installing dependency g++-$CCKERNEL"
-      fi
+      apt-get install g++-$CCKERNEL -y || die "Error installing dependency g++-$CCKERNEL"
     fi
   fi
 
@@ -382,9 +334,7 @@ Missing dependency g++-$CCKERNEL, marking for installation.
   if test "x$dvb_path" = "x"; then
     if ! find /lib/modules/`uname -r`/updates -name dvb-core.ko -print | grep "dvb-core.ko" > /dev/null 2>&1; then
       if uname -a | grep 'Debian' > /dev/null  2>&1; then
-        ./kernelpatch-debian
-      elif uname -a | grep 'Ubuntu' > /dev/null  2>&1; then
-        ./kernelpatch-ubuntu
+        ./kernelpatch
       fi
     fi
     if [ $(echo $?) -eq 1 ]; then
@@ -406,7 +356,7 @@ Aborting...
 fi
 
 #
-# End Debian/Ubuntu Section
+# End Debian Section
 #
 
 
@@ -630,7 +580,7 @@ echo "CXX=$CXX" >> config.mak
 # Compile and, if running Debian/Ubuntu,
 # finish by installing the lot.
 
-if [ $OS == Ubuntu ] || [ $OS == Debian ] ; then
+if [ $OS == Debian ] ; then
   echo "
 
 Everything looks ok!
@@ -648,60 +598,31 @@ Do you want to install ffdecsawrapper binary and dvbloopback kernel module?
 "
       confirmyes "Yes, install them now![Y/n]"
       if [ $(echo $?) -eq 0 ]; then
-        if [ $OS == Debian ] ; then
-          if ps -C ffdecsawrapper > /dev/null 2>&1; then
-            if test -e /etc/init.d/ffdecsawrapper; then
-              /etc/init.d/ffdecsawrapper stop
-              sleep 3
-              rmmod dvbloopback > /dev/null 2>&1
-            else
-              killall -9 ffdecsawrapper
-              sleep 3
-              rmmod dvbloopback > /dev/null 2>&1
-            fi
+        if ps -C ffdecsawrapper > /dev/null 2>&1; then
+          if test -e /etc/init.d/ffdecsawrapper; then
+            /etc/init.d/ffdecsawrapper stop
+            sleep 3
+            rmmod dvbloopback > /dev/null 2>&1
+          else
+            killall -9 ffdecsawrapper
+            sleep 3
+            rmmod dvbloopback > /dev/null 2>&1
           fi
-          rm -f /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
-          rm -f /usr/bin/ffdecsawrapper
-          cp -f ffdecsawrapper /usr/bin
-          mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper
-          /usr/bin/install dvbloopback.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
-          if [ $(echo $?) -eq 0 ]; then
-            depmod -a
-            echo "
+        fi
+        rm -f /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
+        rm -f /usr/bin/ffdecsawrapper
+        cp -f ffdecsawrapper /usr/bin
+        mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper
+        /usr/bin/install dvbloopback.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
+        if [ $(echo $?) -eq 0 ]; then
+          depmod -a
+          echo "
 Installed without errors!
 "  
-          else
-            echo "
-Error(s) encoutered installing the dvbloopback kernel module.
-"
-          fi
         else
-          if ps -C ffdecsawrapper > /dev/null 2>&1; then
-            if test -e /etc/init.d/ffdecsawrapper; then
-              sudo /etc/init.d/ffdecsawrapper stop
-              sudo sleep 3
-              sudo rmmod dvbloopback > /dev/null 2>&1
-            else
-              sudo killall -9 ffdecsawrapper
-              sudo sleep 3
-              sudo rmmod dvbloopback > /dev/null 2>&1
-            fi
-          fi
-          sudo rm -f /lib/modules/`uname -r`/updates/ffdecsawrapper/dvbloopback.ko
-          sudo rm -f /usr/bin/ffdecsawrapper
-          sudo cp -f ffdecsawrapper /usr/bin
-          sudo mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper
-          sudo /usr/bin/install dvbloopback.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
-          if [ $(echo $?) -eq 0 ]; then
-            sudo depmod -a
-            echo "
-Installed without errors!
-"  
-          else
-            echo "
+          echo "
 Error(s) encoutered installing the dvbloopback kernel module.
 "
-          fi
         fi
       fi
     fi
