Move installing build-deps for Debian out of configure

diff --git a/kernelpatch-debian b/kernelpatch-debian
--- a/kernelpatch-debian
+++ b/kernelpatch-debian
@@ -53,19 +53,61 @@ if [ $FIRST_DIGIT -lt 3 ]; then
   exit 1
 fi
 
+# Install dependencies
+
+if echo $OS | grep 'Debian' 2>&1 1>/dev/null; then
+
+  if ! dpkg-query -l libv4l-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libv4l-dev, marking for installation.
+"
+    apt-get install libv4l-dev -y || die "Error installing dependency libv4l-dev"
+  fi
+
+  if ! dpkg-query -l libproc-processtable-perl > /dev/null 2>&1; then
+    echo "
+Missing dependency libproc-processtable-perl, marking for installation.
+"
+    apt-get install libproc-processtable-perl -y || die "Error installing dependency libproc-processtable-perl"
+  fi
+
+  if ! dpkg-query -l libssl-dev > /dev/null 2>&1; then
+    echo "
+Missing dependency libssl-dev, marking for installation.
+"
+    apt-get install libssl-dev -y || die "Error installing dependency libssl-dev"
+  fi
+
+  if ! dpkg-query -l build-essential > /dev/null 2>&1; then
+    echo "
+Missing dependency build-essential, marking for installation.
+"
+    apt-get install build-essential -y || die "Error installing dependency build-essential"
+  fi
+
+  if uname -a | grep 'Debian' > /dev/null  2>&1; then
+    if ! dpkg-query -l linux-headers-`uname -r` > /dev/null 2>&1; then
+      echo "
+Missing dependency linux-headers-`uname -r`, marking for installation.
+"
+      apt-get install linux-headers-`uname -r` -y  || die "Error installing dependency linux-headers-`uname -r`"
+    fi
+  fi
+
+
 # When using ffdecsawrapper, the kernel has to be patched.
 # Let's do it.
 
   BUILD_DIR=/lib/modules/`uname -r`/build
   TEMPDIR=/usr/src/$SHORT_KERNEL
 
-echo "\nFFdecsawrapper needs a patched dvb-core.ko kernel module.\nIf you are running a !!!UNMODIFIED!!! Debian kernel (including those frome 'backports' or other branches, like 'sid'), I can do that for you, if your sources.list is ok and the source for your kernel is available in the repo's.\n\n"
+  echo "\nFFdecsawrapper needs a patched dvb-core.ko kernel module.\nIf you are running a !!!UNMODIFIED!!! Debian kernel (including those frome 'backports' or other branches, like 'sid'), I can do that for you, if your sources.list is ok and the source for your kernel is available in the repo's.\n\n"
 
-confirmyes "Do you want me to patch your running Debian kernel?[Y/n]"
+  confirmyes "Do you want me to patch your running Debian kernel?[Y/n]"
 
-if [ $(echo $?) -eq 0 ]; then
+  if [ $(echo $?) -eq 0 ]; then
 
-  echo "
+    echo "
 
    WARNING!!!
 
@@ -88,51 +130,49 @@ Don't forget to reboot to load new module once you are
 done patching the kernel and compiling ffdecsawrapper and ffdecsawrapper module.
 "
 
-  confirmyes "Proceed?[Y/n]"
+    confirmyes "Proceed?[Y/n]"
 
-
-
-  if [ $(echo $?) -eq 0 ]; then
-    apt-get purge linux-source* -y && apt-get build-dep linux --no-install-recommends -y
-    apt-get install linux-source-$SHORT_KERNEL -y || die "Error installing linux-source-$SHORT_KERNEL"
-    echo "
+    if [ $(echo $?) -eq 0 ]; then
+      apt-get purge linux-source* -y && apt-get build-dep linux --no-install-recommends -y
+      apt-get install linux-source-$SHORT_KERNEL -y || die "Error installing linux-source-$SHORT_KERNEL"
+      echo "
 Building patched dvb-core module for kernel `uname -r`
 
 Preparing, this may take a while...
 "
-    rm -rf $TEMPDIR
-    mkdir -p $TEMPDIR
-    if  [ $FIRST_DIGIT -eq 3 ]; then
-      if [ $SECOND_DIGIT -lt 7 ]; then
-        tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
-        echo "
+      rm -rf $TEMPDIR
+      mkdir -p $TEMPDIR
+      if  [ $FIRST_DIGIT -eq 3 ]; then
+        if [ $SECOND_DIGIT -lt 7 ]; then
+          tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
+          echo "
 Building and installing, please be patient...
 "
-        patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
-        make -C $BUILD_DIR M=$TEMPDIR modules
-        rm -f /lib/modules/`uname -r`/updates/dvb/dvb-core/dvb-core.ko > /dev/null 2>&1
-        mkdir -p /lib/modules/`uname -r`/updates/dvb/dvb-core > /dev/null 2>&1
-        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/dvb/dvb-core
-        rm -rf $TEMPDIR
-        depmod -a
-      else
-        if  test -f /usr/src/linux-source-$SHORT_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-        elif test -f /usr/src/linux-source-$SHORT_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$SHORT_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+          patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
+          make -C $BUILD_DIR M=$TEMPDIR modules
+          rm -f /lib/modules/`uname -r`/updates/dvb/dvb-core/dvb-core.ko > /dev/null 2>&1
+          mkdir -p /lib/modules/`uname -r`/updates/dvb/dvb-core > /dev/null 2>&1
+          /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/dvb/dvb-core
+          rm -rf $TEMPDIR
+          depmod -a
+        else
+          if  test -f /usr/src/linux-source-$SHORT_KERNEL.tar.bz2; then
+            tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+          elif test -f /usr/src/linux-source-$SHORT_KERNEL.tar.xz; then
+            tar -xJf /usr/src/linux-source-$SHORT_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
+          fi
+          echo "
+Building and installing, please be patient...
+"
+          patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
+          make -C $BUILD_DIR M=$TEMPDIR modules
+          rm -f /lib/modules/`uname -r`/updates/dvb-core/dvb-core.ko > /dev/null 2>&1
+          mkdir -p /lib/modules/`uname -r`/updates/dvb-core > /dev/null 2>&1
+          /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/dvb-core
+          rm -rf $TEMPDIR
+          depmod -a
         fi
-        echo "
-Building and installing, please be patient...
-"
-        patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
-        make -C $BUILD_DIR M=$TEMPDIR modules
-        rm -f /lib/modules/`uname -r`/updates/dvb-core/dvb-core.ko > /dev/null 2>&1
-        mkdir -p /lib/modules/`uname -r`/updates/dvb-core > /dev/null 2>&1
-        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/dvb-core
-        rm -rf $TEMPDIR
-        depmod -a
       fi
     fi
   fi
 fi
-
