Update kernelpatching routine (so it should work on Ubuntu with backported kernels now) refs #21

diff --git a/kernelpatch b/kernelpatch
--- a/kernelpatch
+++ b/kernelpatch
@@ -38,7 +38,7 @@ success(){
 depmod -a
 echo -en "
 
-###################################################################
+####################################################################
 \E[1;33;44mYour kernel is properly patched. You should reboot your machine now.\E[0m
 ####################################################################
 "
@@ -103,7 +103,7 @@ Aborting...
 # Define where to build and from what dir to build
 
     BUILD_DIR="/lib/modules/`uname -r`/build"
-    TEMPDIR="/usr/src/$SHORT_KERNEL"
+    TEMPDIR="tmp"
 
 
 # Abort if running kernel is < 3.x
@@ -151,83 +151,50 @@ will be patched for use with ffdecsawrapper.
 
   if [ "$?" -eq 0 ]; then
     apt-get build-dep linux --no-install-recommends -y || die "Error installing \"build-dep linux\""
-    if [ "$OS" == Debian ]; then
-      apt-get --reinstall install linux-source-$SHORT_KERNEL -y || die "Error installing linux-source-$SHORT_KERNEL"
-    else
-      apt-get --reinstall install linux-source-$UBUNTU_KERNEL -y || die "Error installing linux-source-$UBUNTU_KERNEL"
-    fi
-
-# Compile the patched dvb-core.ko module and install it
-
-    echo "
-Building patched dvb-core module for kernel `uname -r`
-
-Preparing, this may take a while...
-"
-    rm -rf $TEMPDIR
-    mkdir -p $TEMPDIR
+    rm -rf $TEMPDIR && mkdir $TEMPDIR && cd $TEMPDIR && apt-get source linux-image-`uname -r` -y || die "Error installing linux-source-$UBUNTU_KERNEL"
+    cd linux*
+    CWD=$(pwd)
     if  [ "$FIRST_DIGIT" -eq 3 ]; then
       if [ "$SECOND_DIGIT" -lt 7 ]; then
-        if  test -f /usr/src/linux-source-$SHORT_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
-        elif  test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 5 linux-source-$UBUNTU_KERNEL/drivers/media/dvb/dvb-core/
-        elif test -f /usr/src/linux-source-$SHORT_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$SHORT_KERNEL.tar.xz -C $TEMPDIR --strip-components 5 linux-source-$SHORT_KERNEL/drivers/media/dvb/dvb-core/
-        elif test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz -C $TEMPDIR --strip-components 5 linux-source-$UBUNTU_KERNEL/drivers/media/dvb/dvb-core/
+        patch -p0 < ../../linux-2.6.38-dvb-mutex.patch
+        if [ "$?" -eq 0 ]; then
+          success
+        else
+          fail
         fi
-        echo "
-Building and installing
-"
-        patch -p5 -d $TEMPDIR < linux-2.6.38-dvb-mutex.patch > /dev/null 2>&1
-        CC="$GCC" make -C $BUILD_DIR M=$TEMPDIR modules
+        CC="$GCC" make -C $BUILD_DIR M=$CWD/drivers/media/dvb/dvb-core modules
         mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper > /dev/null 2>&1
-        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
+        /usr/bin/install $CWD/drivers/media/dvb/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
         if [ "$?" -eq 0 ]; then
           success
         else
           fail
         fi
       elif [ "$SECOND_DIGIT" -lt 13 ]; then
-        if  test -f /usr/src/linux-source-$SHORT_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-        elif  test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$UBUNTU_KERNEL/drivers/media/dvb-core/
-        elif test -f /usr/src/linux-source-$SHORT_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$SHORT_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-        elif test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$UBUNTU_KERNEL/drivers/media/dvb-core/
+        patch -p0 < ../../linux-3.7.1-dvb-mutex.patch
+        if [ "$?" -eq 0 ]; then
+          success
+        else
+          fail
         fi
-        echo "
-Building and installing
-"
-        patch -p4 -d $TEMPDIR < linux-3.7.1-dvb-mutex.patch > /dev/null 2>&1
-        CC="$GCC" make -C $BUILD_DIR M=$TEMPDIR modules
+        CC="$GCC" make -C $BUILD_DIR M=$CWD/drivers/media/dvb-core modules
         mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper > /dev/null 2>&1
-        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
+        /usr/bin/install $CWD/drivers/media/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
         if [ "$?" -eq 0 ]; then
           success
         else
           fail
         fi
       else
-        if  test -f /usr/src/linux-source-$SHORT_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$SHORT_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-        elif  test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2; then
-          tar -xjf /usr/src/linux-source-$UBUNTU_KERNEL.tar.bz2 -C $TEMPDIR --strip-components 4 linux-source-$UBUNTU_KERNEL/drivers/media/dvb-core/
-        elif test -f /usr/src/linux-source-$SHORT_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$SHORT_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$SHORT_KERNEL/drivers/media/dvb-core/
-        elif test -f /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz; then
-          tar -xJf /usr/src/linux-source-$UBUNTU_KERNEL.tar.xz -C $TEMPDIR --strip-components 4 linux-source-$UBUNTU_KERNEL/drivers/media/dvb-core/
+        patch -p0 < ../../linux-3.13-dvb-mutex.patch
+        if [ "$?" -eq 0 ]; then
+          success
+        else
+          fail
         fi
-        echo "
-Building and installing
-"
-        patch -p4 -d $TEMPDIR < linux-3.13-dvb-mutex.patch > /dev/null 2>&1
-        CC="$GCC" make -C $BUILD_DIR M=$TEMPDIR modules
+        CC="$GCC" make -C $BUILD_DIR M=$CWD/drivers/media/dvb-core modules
         mkdir -p /lib/modules/`uname -r`/updates/ffdecsawrapper > /dev/null 2>&1
-        /usr/bin/install $TEMPDIR/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
+        /usr/bin/install $CWD/drivers/media/dvb-core/dvb-core.ko /lib/modules/`uname -r`/updates/ffdecsawrapper
         if [ "$?" -eq 0 ]; then
           success
         else
