Fix previous commit

diff --git a/contrib/sasc-ng/configure b/contrib/sasc-ng/configure
--- a/contrib/sasc-ng/configure
+++ b/contrib/sasc-ng/configure
@@ -127,18 +127,21 @@ done
 
 if [ $FIRST_DIGIT -eq 3 ]; then
   if [ $SECOND_DIGIT -lt 7 ]; then
-    echo "3.6.x or lower kernel detected"
+    echo "3.6.x or lower kernel detected."
   else
-    echo "3.7.x or higher kernel detected"
+    echo "3.7.x or higher kernel detected."
   fi
 elif [ $FIRST_DIGIT -eq 2 ]; then
   if [ $SECOND_DIGIT -lt 6 ]; then
     echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
     exit 1
-  if [ $SECOND_DIGIT -eq 6 ]; then
-    if [ $PATCHLEVEL -lt 38 ]; then
-      echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
-      exit 1
+    if [ $SECOND_DIGIT -eq 6 ]; then
+      if [ $PATCHLEVEL -lt 38 ]; then
+        echo "The kernel you are running is not supported anymore.\n\nMinimum supported version is 2.6.38\n\nAborting..."
+        exit 1
+      else
+        echo "2.6.38 or higher kernel detected."
+      fi
     fi
   fi
 fi
